### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Gogoseit2020** [BD103/TickLowerPerm#5]
not sure of this would be possible, or very practical to do, but it would be very useful to be able to run commands in the command blocks even when time is frozen

**Comment by BD103** [comment]
Hi! I don't believe this is possible, because command blocks run by being ticked. Freezing the game prevents these ticks from happening, and I could see scenarios where people actually want this too.

I don't know your exact circumstances, but look into creating a [data pack](https://minecraft.wiki/w/Data_pack) instead! They may be able to work around these restrictions.
